### ISSUE TITLE
Model.findOrCreate rejects with error

### ISSUE THREAD

**Issue by lekoder** [cockroachdb/sequelize-cockroachdb#16] opened 2017-09-21 08:29 UTC
When trying to use `Model.findOrCreate`, sequelize rejects operation with:

```
SequelizeDatabaseError: syntax error at or near "or"
CREATE OR REPLACE FUNCTION pg_temp.testfunc( [...]
       ^
```
sequelize: **4.8.4**
sequelize-cockroachdb **1.0.2**

**Comment by benesch** [comment] 2017-09-22 17:49
Sorry about this! This looks to be a duplicate of #15, though, so closing to centralize discussion there.

**Closed by benesch** 2017-09-22 17:49 UTC
