### ISSUE TITLE
Allow UPSERT...RETURNING

### ISSUE THREAD

**Issue by justinj** [cockroachdb/sequelize-cockroachdb#22] opened 2018-02-20 15:24 UTC
As of #17149, we support `UPSERT...RETURNING`, but this module still blocks its use.

**Comment by rafiss** [comment] 2020-08-04 18:28
duplicate of https://github.com/cockroachdb/sequelize-cockroachdb/issues/24

**Closed by rafiss** 2020-08-04 18:28 UTC
